### ISSUE TITLE
Nerfing of the stock ion engine

### ISSUE THREAD

**Issue by pyalot** [ChrisAdderley/NearFuturePropulsion#14]
It's kinda annoying if a mod degrades a stock part substantially. Is it really necessary?

**Comment by lOmicronl** [comment]
Yes, it is really necessary.

The Dawn engine is possibly the most overpowered engine in all of KSP, by raw stats alone. It is rarely noticed, however, for three reasons: one, the mass ratio of xenon tanks is unrealistically low, putting the brakes on the engine's performance scaling. Two, it's also one of the least used engines beause most players severely dislike burns taking longer than a few minutes. Since the low thrust of the Dawn mandates long burns, even great performance otherwise does not compel people enough to really abuse it. Three, the stock KSP solar system is so small, and its velocities so low, that the sheer potential of the Dawn simply isn't required. There are no missions you cannot fly with chemical propellant - even the LV-N is generally only strictly *required* for grand tours. The fact that launch vehicles have payload fractions around five times higher than IRL only makes it even easier.

However, this does become a problem for mods that want to add additional electric engines. Particularly if those other engines are supposed to be more modern than the Dawn, which is a nod to the NSTAR ion drives used on NASA's Deep Space 1 and Dawn spacecrafts (hence the name). That's an old design with very low power intake and performance alike, used to validate that deep space missions with electric propulsion are even a valid option at all. All newer and more powerful electric engines thus need to outperform the Dawn, if you want to keep nodding to IRL technology.

Of ourse, there's the option of not nodding to IRL technology, to just make up some weaker eletric engines to add as precursors to the Dawn. However, you cannot do this, beause the stock tech tree does not support it. For one, the Dawn engine sits in a node called "Ion Propulsion". How can you justify adding any ion drives in nodes coming *before* and leading up to that node? It just looks awful and immersion-breaking. This is further exacerbated by what you see when you look into those lead-up nodes and check the parts that are there. None of them have any relation whatsoever to the kind of technology required to produce any of the various sorts of ion/plasma thruster devices. Now, since KSP 1.0, there is one new node on the tier before - called "High-Power Electrics" - which does fit the bill to some extent in at least the naming. Unfortunately, this node does not lead up to Ion Propulsion at all; it's a different branch altogether. So any engines placed there can not be based on similar technology as the Dawn. RLA Stockalike, for instance, uses this node to carry a resistojet and an arcjet thruster. Both are distinctly different technologies from elecrostatic ion thrusters; one is a thermal engine like the LV-N, the other just shoves propellant through a tesla coil (metaphorically speaking). Thus they make sense to be both slightly more primitive and to be technologically unrelated.

To sum up, the only option you have is to take the Dawn as the baseline entry point of your engine progression and add engines that are either equivalent in power, or exceed it. Because of what the Dawn is meant to represent, most must logically exceed it. And if the entry baseline is so very high, all engines that exceed it will be even more absurd. You quickly encounter the point where they are simply the best option for every job, all the time, as opposed to having their uses while still leaving niches to the LV-N and the chemical engines. Since the Near Future suite as a whole is designed to remain fairly close to stock in its design approach (as opposed to, say, KSP Interstellar, which is quite far from stock), rendering stock engines and mechanics irrelevant is not desirable.

Thus the decision was made to patch the Dawn engine and, in doing so, to bring down the baseline for all electric engines in order to afford a sensible power progression that conforms to stock KSP performance envelopes. It's not something we're fond of, but ever since Squad decided to buff the Dawn's performance by 800% in 0.23.5, it has been a necessity for the reasons outlined above. Consider it a small tradeoff to be made to provide a much better gameplay experience overall.

**Comment by pyalot** [comment]
I suspected that was the reason, thanks for the explanation. Maybe put a short description in the readme which engines have been nerfed and how (and a sentence or two as to why).

**Comment by lOmicronl** [comment]
It's in the FAQ section in the opening post of the mod thread on the KSP forums.
